"use client";
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define the structure for the sign-in payload
export type SignInPayload = {
  email: string;
  password: string;
};

export const authApi = createApi({
  reducerPath: "authApi",
  baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:4000" }),
  endpoints: (builder) => ({
    signIn: builder.mutation<any, SignInPayload>({
      query: ({ email, password }) => ({
        url: "/auth/SignIn", // Endpoint path relative to baseQuery URL
        method: "POST",
        body: { email, password }, // Payload structure
      }),
    }),
    login: builder.mutation<any, SignInPayload>({
      query: ({ email, password }) => ({
        url: "/auth/login", // Endpoint path relative to baseQuery URL
        method: "POST",
        body: { email, password }, // Payload structure
      }),
    }),
  }),
});

// Export the hooks generated by RTK Query
export const { useSignInMutation, useLoginMutation } = authApi;